Library App
Laguna1/Library pull request #3
Opened 2020-11-23 18:04 UTC by Laguna1

2020-11-23 20:28 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
#### Hi @pbkabali and @Laguna1 :clap: :clap:
#### The webpage looks great. You have done a good job of implementing a good user interface. However, some requirements are missing/not implemented correctly. Check my comments below :point_down: for the overview of the required changes and the inline comments for the affected part of the code.

##### Project Configuration:
- **_The package.json file is missing which means this is not well configured. You can run `npm init` so that the package.json file will be added._**

##### Dom Manipulation
- **_The application logic should be separated from DOM manipulation tasks ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png) from Pathwright)_**

- **_The styling logic should be in CSS files_**

##### Readme:
- **_Add instruction on how to clone and run the project locally._**

#### Optional
- **_Add validations to the form, user would not be able to create an empty book_**

- **_You can add data persistence by saving, retrieving, and updating the library books using [the localstorage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/localstorage_stretch_requirement.png) from [Odin Project](https://www.theodinproject.com/courses/javascript/lessons/library))_**

- **_Try as much as you can to avoid disabling ESLint rules. However, instead of disabling the same rules in several places, disable it once so that it applies to all the affected parts._**

#### _Reviewed by Temitayo Adeleke_

2020-11-23 20:28 UTC, lekegitrepo commented on static/js/main.js
> +  newBookForm.style.display = 'flex';
- **_The styling logic should be in CSS files_**

2020-11-23 20:28 UTC, lekegitrepo commented on static/js/main.js
> +  newBookForm.style.display = 'none';
- **_The styling logic should be in CSS files_**

2020-11-23 20:28 UTC, lekegitrepo commented on static/js/main.js
> +  newBookForm.style.display = 'none';
- **_The styling logic should be in CSS files_**

2020-11-24 00:29 UTC, Laguna1 commented
Thank you for the review, @lekegitrepo.  We have worked on the feedback and requested another review.

2020-11-24 00:39 UTC, rOluochKe approved these changes
### You got it right, well done. The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-11-25 14:49 UTC, merged